version: "3"
services:
  runner:
    image: angr/azure-runner
    deploy:
      replicas: 10
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - AZP_URL=https://dev.azure.com/angr
      - AZP_TOKEN
